# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Europe/Berlin"
    groups:
      uefi:
        patterns:
          - "uefi*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Europe/Berlin"
